# Generated by Django 4.0 on 2022-02-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AA',
            fields=[
                ('m_number', models.IntegerField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(blank=True, max_length=45, null=True)),
                ('m_lcc', models.CharField(blank=True, max_length=45, null=True)),
                ('m_lcn', models.CharField(blank=True, max_length=45, null=True)),
                ('m_mcc', models.CharField(blank=True, max_length=45, null=True)),
                ('m_mcn', models.CharField(blank=True, max_length=45, null=True)),
                ('m_scc', models.CharField(blank=True, max_length=45, null=True)),
                ('m_scn', models.CharField(blank=True, max_length=45, null=True)),
                ('c_code', models.IntegerField(blank=True, null=True)),
                ('c_name', models.CharField(blank=True, max_length=45, null=True)),
                ('gg_code', models.IntegerField(blank=True, null=True)),
                ('gg_name', models.CharField(blank=True, max_length=45, null=True)),
                ('ad_name', models.CharField(blank=True, max_length=45, null=True)),
                ('st_name', models.CharField(blank=True, max_length=45, null=True)),
                ('stad_name', models.CharField(blank=True, max_length=45, null=True)),
                ('o_mb', models.IntegerField(blank=True, null=True)),
                ('n_mb', models.IntegerField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si', models.CharField(max_length=30)),
                ('gu', models.CharField(max_length=30)),
                ('dong', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'quickstart_chart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeoulPplDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu', models.TextField(blank=True, null=True)),
                ('dong', models.TextField(blank=True, null=True)),
                ('house', models.IntegerField(blank=True, null=True)),
                ('all_sum', models.IntegerField(blank=True, null=True)),
                ('male', models.IntegerField(blank=True, null=True)),
                ('female', models.IntegerField(blank=True, null=True)),
                ('korean', models.IntegerField(blank=True, null=True)),
                ('k_male', models.IntegerField(blank=True, null=True)),
                ('k_pemale', models.IntegerField(blank=True, null=True)),
                ('fore', models.IntegerField(blank=True, null=True)),
                ('f_male', models.IntegerField(blank=True, null=True)),
                ('f_peemale', models.IntegerField(blank=True, null=True)),
                ('ppl_house', models.IntegerField(blank=True, null=True)),
                ('old', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seoul_ppl_dong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=30)),
                ('m_lcc', models.CharField(max_length=30)),
                ('m_mcc', models.CharField(max_length=30)),
                ('m_scc', models.CharField(max_length=30)),
            ],
        ),
    ]
